In [ ]:
import pandas as pd
import os
import requests
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

data_path = '../../datasets/alexa-top-1m/top-1m.csv'
chunks_folder = '../../datasets/alexa-top-1m/chunks'
chunks_2nd_attempt_folder = '../../datasets/alexa-top-1m/chunks/2nd_attempt'
chunks_with_vpn_folder = '../../datasets/alexa-top-1m/chunks/2nd_attempt/with_vpn'

df = pd.read_csv(data_path, index_col=0).reset_index(drop=True)

df

                        url
0                google.com
1               youtube.com
2              facebook.com
3                 baidu.com
4             wikipedia.org
...                     ...
999995             sibf.org
999996         bukapintu.co
999997        klatovynet.cz
999998  elconquistadorfm.cl
999999    laputertienda.com

[1000000 rows x 1 columns]

In [2]:
df.describe()

               url
count      1000000
unique     1000000
top     google.com
freq             1

In [3]:
# splitting the data into chunks (50 chunks) (the process takes too long, even for a chunk)

chunk_size = len(df) // 50

chunks =  [df.iloc[i:i+chunk_size] for i in range(0, len(df), chunk_size)]

In [4]:
print(f'number of chunks {len(chunks)}')
for chunk in chunks:
  print(chunk.shape)

number of chunks 50
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)
(20000, 1)

In [ ]:
domain = "google.com.eg"
response = requests.get(
    f"https://{domain}",
    allow_redirects=True,
    headers={"User-Agent": "Mozilla/5.0"}
)
print("Final URL:", response.url)
print("Resolved domain:", urlparse(response.url).netloc)

Final URL: https://www.google.com/
Resolved domain: www.google.com

In [ ]:
def resolve_url(bare_domain, timeout=10):
  """
  Takes a bare domain, eg: google.com, tries to send a request to that domain with https then http scheme
  The result will be a resolved domain, eg: https://www.google.com/
  """
  try:
    response = requests.get(
      f"https://{bare_domain}",
      timeout=timeout,
      allow_redirects=True,
      headers={"User-Agent": "Mozilla/5.0"}
    )
    return response.url
  except requests.exceptions.SSLError:
    try:
      response = requests.get(
        f"http://{bare_domain}",
        timeout=timeout,
        allow_redirects=True,
        headers={"User-Agent": "Mozilla/5.0"}
      )
      return response.url
    except:
      return None
  except:
    return None

In [ ]:
def process_chunk(chunk, sub_chunk_size=None, max_workers=100):
  """
  Process a single chunk of URLs concurrently with threads.
  If sub_chunk_size is specified then the chunk will be farther splitted into sub chunks and processed
  """
  if sub_chunk_size:
    sub_chunks = [chunk.iloc[i:i+sub_chunk_size] for i in range(0, len(chunk), sub_chunk_size)]
    results = []
    for sub_chunk in sub_chunks:
      resolved_urls = 0
      sub_results = [None] * len(sub_chunk)
      with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(resolve_url, sub_chunk.iloc[i]): i for i in range(len(sub_chunk))}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Resolving sub chunk"):
          idx = futures[future]
          sub_results[idx] = future.result()
          resolved_urls += future.result() is not None
      print(f'{resolved_urls} url resolved')
      results.extend(sub_results)
    return results
  else:
    resolved_urls = 0
    results = [None] * len(chunk)
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
      futures = {executor.submit(resolve_url, chunk.iloc[i]): i for i in range(len(chunk))}
      for future in tqdm(as_completed(futures), total=len(futures), desc="Resolving chunk"):
        idx = futures[future]
        results[idx] = future.result()
        resolved_urls += future.result() is not None
    print(f'{resolved_urls} url resolved')
    return results

In [ ]:
def resolve_df_urls(df, chunks_folder, chunk_size=5000, sub_chunk_size=None, max_workers=100):
  """
  Resolves all URLs in a DataFrame in chunks with threading.
  Returns the DataFrame with a new column 'resolved_url'.
  """    
  chunks = [df.iloc[i:i+chunk_size] for i in range(0, len(df), chunk_size)]

  processed_chunks = []
  for file in os.listdir(chunks_folder):
    if file.endswith('.csv'):
      processed_chunks.append(int(file.split('.')[0].split('_')[1]))

  for i, chunk in enumerate(chunks):
    if i in processed_chunks:
      continue
    print(f"Processing chunk {i + 1}/{len(chunks)} ({len(chunk)} URLs)")
    chunk_results = process_chunk(chunk['url'], sub_chunk_size=sub_chunk_size, max_workers=max_workers)
    chunk['resolved_url'] = chunk_results
    chunk.to_csv(f'{chunks_folder}/chunk_{i}.csv')

In [ ]:
resolve_df_urls(df, chunks_folder, chunk_size=20000, sub_chunk_size=5000, max_workers=100)

In [ ]:
resolved_chunks = []

for file in os.listdir(chunks_folder):
  if file.endswith('.csv'):
    resolved_chunks.append(pd.read_csv(f'{chunks_folder}/{file}', index_col=0).reset_index(drop=True))

resolved_df = pd.concat(resolved_chunks)

resolved_df

                             url                        resolved_url
0      buenosairescompras.gob.ar  https://buenosairescompras.gob.ar/
1            furuitang.tmall.com                                 NaN
2                 zhujinwang.com                                 NaN
3                     aeipro.com                                 NaN
4                technokarak.com            https://technokarak.com/
...                          ...                                 ...
19995                 lierse.com             https://www.lierse.com/
19996               poporo.ne.jp                                 NaN
19997         scuolasicurezza.it                                 NaN
19998                 km43yy.com                                 NaN
19999               cool-boom.ru                                 NaN

[1000000 rows x 2 columns]

In [12]:
# resolved VS unresolved URLs
total_rows = resolved_df.shape[0]
f'{(~resolved_df['resolved_url'].isna()).sum()} of {total_rows} resolved VS {resolved_df['resolved_url'].isna().sum()} of {total_rows} unresolved'

'628354 of 1000000 resolved VS 371646 of 1000000 unresolved'

In [13]:
# resolved VS unresolved URLs percentage
f'{(round((~resolved_df['resolved_url'].isna()).sum() / total_rows * 100))}% of {total_rows} resolved VS {round(resolved_df['resolved_url'].isna().sum() / total_rows * 100)}% of {total_rows} unresolved'

'63% of 1000000 resolved VS 37% of 1000000 unresolved'

In [14]:
unresolved_chunks = []

for chunk in resolved_chunks:
  unresolved_chunks.append(
    chunk[chunk['resolved_url'].isna()]
  )

In [15]:
unresolved_df = pd.concat(unresolved_chunks).reset_index(drop=True)

unresolved_df

                            url resolved_url
0           furuitang.tmall.com          NaN
1                zhujinwang.com          NaN
2                    aeipro.com          NaN
3       automotivemileposts.com          NaN
4                       bta.com          NaN
...                         ...          ...
371641           ignition.co.za          NaN
371642             poporo.ne.jp          NaN
371643       scuolasicurezza.it          NaN
371644               km43yy.com          NaN
371645             cool-boom.ru          NaN

[371646 rows x 2 columns]

In [16]:
for i in range(2, len(unresolved_df)):
  if len(unresolved_df) % i == 0:
    print(i)

2
3
6
9
11
18
22
33
66
99
198
1877
3754
5631
11262
16893
20647
33786
41294
61941
123882
185823

In [17]:
len(unresolved_df) / 22

16893.0

In [18]:
for i in range(2, 16893):
  if 16893 % i == 0:
    print(i)

3
9
1877
5631

In [19]:
16893 / 3

5631.0

In [ ]:
# second attempt for unresolved urls

chunk_size = len(unresolved_df) // 22
sub_chunk_size = chunk_size // 3

resolve_df_urls(unresolved_df, chunks_2nd_attempt_folder, chunk_size=chunk_size, sub_chunk_size=sub_chunk_size, max_workers=100)

Processing chunk 15/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:19<00:00,  5.75it/s]

892 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:50<00:00,  5.57it/s]

815 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:17<00:00,  5.76it/s]

552 url resolved
Processing chunk 16/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:14<00:00,  5.78it/s]

330 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [15:52<00:00,  5.91it/s]

660 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:02<00:00,  5.85it/s]

551 url resolved
Processing chunk 17/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:20<00:00,  5.74it/s]

358 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:00<00:00,  5.86it/s]

502 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:03<00:00,  5.84it/s]

682 url resolved
Processing chunk 18/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:08<00:00,  5.82it/s]

683 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:27<00:00,  5.70it/s]

616 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [15:47<00:00,  5.94it/s]

679 url resolved
Processing chunk 19/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:41<00:00,  5.62it/s]

755 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:04<00:00,  5.84it/s]

1019 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:17<00:00,  5.76it/s]

531 url resolved
Processing chunk 20/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [17:04<00:00,  5.50it/s]

563 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:27<00:00,  5.70it/s]

681 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:13<00:00,  5.79it/s]

531 url resolved
Processing chunk 21/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:08<00:00,  5.82it/s]

482 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:38<00:00,  5.64it/s]

661 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [16:31<00:00,  5.68it/s]

914 url resolved
Processing chunk 22/22 (16893 URLs)

Resolving sub chunk: 100%|██████████| 5631/5631 [16:38<00:00,  5.64it/s]

1040 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [14:44<00:00,  6.36it/s]

1004 url resolved

Resolving sub chunk: 100%|██████████| 5631/5631 [13:43<00:00,  6.84it/s]

861 url resolved

In [21]:
chunks_folder = '../../datasets/alexa-top-1m/chunks/2nd_attempt'
resolved_chunks = []

for file in os.listdir(chunks_folder):
  if file.endswith('.csv'):
    resolved_chunks.append(pd.read_csv(f'{chunks_folder}/{file}', index_col=0).reset_index(drop=True))

In [23]:
resolved_df = pd.concat(resolved_chunks)

resolved_df

                     url                     resolved_url
0           1academy.pro            https://1academy.pro/
1             tuition.io          https://www.tuition.io/
2                kcho.jp                              NaN
3           lefigaro.com                              NaN
4        trendoffset.com                              NaN
...                  ...                              ...
16888  lakhimpurlive.com                              NaN
16889        fuhaotd.com                              NaN
16890     emstock.com.cn                              NaN
16891       new-part.com            https://new-part.com/
16892    hrdownloads.com  https://www.citationcanada.com/

[371646 rows x 2 columns]

In [24]:
# resolved VS unresolved URLs
total_rows = resolved_df.shape[0]
f'{(~resolved_df['resolved_url'].isna()).sum()} of {total_rows} resolved VS {resolved_df['resolved_url'].isna().sum()} of {total_rows} unresolved'

'69249 of 371646 resolved VS 302397 of 371646 unresolved'

In [25]:
# resolved VS unresolved URLs percentage
f'{(round((~resolved_df['resolved_url'].isna()).sum() / total_rows * 100))}% of {total_rows} resolved VS {round(resolved_df['resolved_url'].isna().sum() / total_rows * 100)}% of {total_rows} unresolved'

'19% of 371646 resolved VS 81% of 371646 unresolved'

In [28]:
unresolved_df = resolved_df.loc[resolved_df['resolved_url'].isna(), ['url']].reset_index(drop=True)

unresolved_df

                      url
0                 kcho.jp
1            lefigaro.com
2         trendoffset.com
3             mcit.gov.et
4                h-fg.net
...                   ...
302392     english4me.net
302393     poderdegym.com
302394  lakhimpurlive.com
302395        fuhaotd.com
302396     emstock.com.cn

[302397 rows x 1 columns]

In [30]:
for i in range(2, len(unresolved_df)):
  if len(unresolved_df) % i == 0:
    print(f'{i}: {len(unresolved_df) / i}')

3: 100799.0
100799: 3.0

In [38]:
unresolved_df

                      url
0                 kcho.jp
1            lefigaro.com
2         trendoffset.com
3             mcit.gov.et
4                h-fg.net
...                   ...
302392     english4me.net
302393     poderdegym.com
302394  lakhimpurlive.com
302395        fuhaotd.com
302396     emstock.com.cn

[302397 rows x 1 columns]

In [ ]:
chunk_size = len(unresolved_df) // 20
sub_chunk_size = chunk_size // 3

resolve_df_urls(unresolved_df, chunks_with_vpn_folder, chunk_size=chunk_size, sub_chunk_size=sub_chunk_size, max_workers=100)

Processing chunk 11/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [06:39<00:00, 12.60it/s]

532 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:24<00:00, 24.61it/s]

582 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:57<00:00, 21.18it/s]

326 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:11<00:00,  5.80s/it]

0 url resolved
Processing chunk 12/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [05:11<00:00, 16.15it/s]

621 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:58<00:00, 21.16it/s]

724 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:50<00:00, 21.88it/s]

698 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:14<00:00,  7.19s/it]

0 url resolved
Processing chunk 13/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [03:22<00:00, 24.86it/s]

628 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:20<00:00, 25.08it/s]

474 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:46<00:00, 22.23it/s]

632 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:16<00:00,  8.12s/it]

0 url resolved
Processing chunk 14/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [04:39<00:00, 18.01it/s]

677 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:27<00:00, 24.34it/s]

529 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:55<00:00, 21.37it/s]

713 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:00<00:00,  2.68it/s]

1 url resolved
Processing chunk 15/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [03:41<00:00, 22.76it/s]

736 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:20<00:00, 25.14it/s]

522 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [04:08<00:00, 20.31it/s]

548 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:01<00:00,  1.56it/s]

0 url resolved
Processing chunk 16/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [04:04<00:00, 20.64it/s]

356 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:50<00:00, 21.86it/s]

536 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:41<00:00, 22.73it/s]

628 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:01<00:00,  1.14it/s]

0 url resolved
Processing chunk 17/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [05:50<00:00, 14.39it/s]

572 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:56<00:00, 21.26it/s]

385 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:40<00:00, 22.81it/s]

425 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:10<00:00,  5.16s/it]

0 url resolved
Processing chunk 18/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [04:24<00:00, 19.04it/s]

602 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [05:09<00:00, 16.29it/s]

618 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:54<00:00, 21.51it/s]

354 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

1 url resolved
Processing chunk 19/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [04:07<00:00, 20.35it/s]

511 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [06:38<00:00, 12.66it/s]

619 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [04:29<00:00, 18.66it/s]

574 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:03<00:00,  1.83s/it]

1 url resolved
Processing chunk 20/21 (15119 URLs)

Resolving sub chunk: 100%|██████████| 5039/5039 [03:39<00:00, 22.99it/s]

412 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:33<00:00, 23.65it/s]

473 url resolved

Resolving sub chunk: 100%|██████████| 5039/5039 [03:49<00:00, 21.98it/s]

607 url resolved

Resolving sub chunk: 100%|██████████| 2/2 [00:03<00:00,  1.62s/it]

0 url resolved
Processing chunk 21/21 (17 URLs)

Resolving sub chunk: 100%|██████████| 17/17 [00:10<00:00,  1.63it/s]

4 url resolved